--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Wumpotamus/UHCGames
build-by-default: true
branches:
- master
projects:
  UHCGames:
    path: ""
    libs:
      - src: Wumpotamus/libChunkLoader/libChunkLoader
        version: 2.0.0
    lint:
      phpstan: false
...
