--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/stephen-mc-pl/UHCGames
build-by-default: true
branches:
- master
projects:
  UHCGames:
    path: ""
    libs:
      - src: stephen-mc-pl/libChunkLoader/libChunkLoader
        branch: "4.0"
        version: 3.0.0
    lint:
      phpstan: false
...
